[build]
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev"
  port = 3000

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Explicitly disable any plugins
[[plugins]]
  # No plugins